export const TRANSACTION_INITIALIZE_START = 'TRANSACTION_INITIALIZE_START';
export const TRANSACTION_INITIALIZE_FINISH = 'TRANSACTION_INITIALIZE_FINISH';
export const CHANGE_TIME_SCREEN = 'CHANGE_TIME_SCREEN';