export default transactionListConstants = {
    TRANSACTION_LIST_INITIALIZE_START: 'TRANSACTION_LIST_INITIALIZE_START',
    TRANSACTION_LIST_INITIALIZE_FINISH: 'TRANSACTION_LIST_INITIALIZE_FINISH',
    CHANGE_TIME_SCREEN: 'CHANGE_TIME_SCREEN',
    REMOVE_TRANSACTION: 'REMOVE_TRANSACTION',
    TRANSACTION_LIST_LONG_PRESS: 'TRANSACTION_LIST_LONG_PRESS',
    TRANSACTION_LIST_ACTIVATE_DELETE_MODE: 'TRANSACTION_LIST_ACTIVATE_DELETE_MODE',
    TRANSACTION_LIST_DESACTIVATE_DELETE_MODE: 'TRANSACTION_LIST_DESACTIVATE_DELETE_MODE',
    TRANSACTION_LIST_ADD_TO_DELETE_LIST: 'TRANSACTION_LIST_ADD_TO_DELETE_LIST',
    TRANSACTION_LIST_REMOVE_FROM_DELETE_LIST: 'TRANSACTION_LIST_REMOVE_FROM_DELETE_LIST',
    TRANSACTION_LIST_SET_LIST_BY_CATEGORY: 'TRANSACTION_LIST_SET_LIST_BY_CATEGORY'
}
