export default reportConstants = {
    REPORT_INITIALIZE_START: 'REPORT_INITIALIZE_START',
    REPORT_INITIALIZE_FINISH: 'REPORT_INITIALIZE_FINISH',
    CHANGE_REPORT_MODE: 'CHANGE_REPORT_MODE',
    REPORT_CHANGE_DATE: 'REPORT_CHANGE_DATE',
    REPORT_SET_TRANSACTIONS: 'REPORT_SET_TRANSACTIONS',
    REPORT_SET_ESTADISTICS: 'REPORT_SET_ESTADISTICS',
    REPORT_SET_SELECTED_SLICE: 'REPORT_SET_SELECTED_SLICE',
    REPORT_SET_TOTALS: 'REPORT_SET_TOTALS',
    REPORT_SET_USER_CURRENCY: 'REPORT_SET_USER_CURRENCY'
}
