export const MONEY_MANAGER_INITIALIZE_START = 'MONEY_MANAGER_INITIALIZE_START';
export const MONEY_MANAGER_INITIALIZE_FINISH = 'MONEY_MANAGER_INITIALIZE_FINISH';
export const MONEY_MANAGER_TAB_MODE_CHANGE = 'MONEY_MANAGER_TAB_MODE_CHANGE';