export default moneyManagerConstants = {
    MONEY_MANAGER_INITIALIZE_START: 'MONEY_MANAGER_INITIALIZE_START',
    MONEY_MANAGER_INITIALIZE_FINISH:'MONEY_MANAGER_INITIALIZE_FINISH',
    MONEY_MANAGER_TAB_MODE_CHANGE: 'MONEY_MANAGER_TAB_MODE_CHANGE',
    MONEY_MANAGER_SHOW_SPINNER: 'MONEY_MANAGER_SHOW_SPINNER',
    MONEY_MANAGER_HIDE_SPINNER: 'MONEY_MANAGER_HIDE_SPINNER',
    MONEY_MANAGER_SET_LOCALE: 'MONEY_MANAGER_SET_LOCALE',
    MONEY_MANAGER_SHOW_INTERSTITIAL_AD: 'MONEY_MANAGER_SHOW_INTERSTITIAL_AD'
}
