export default loginConstans = {
    LOGIN_INITIALIZE_START: 'LOGIN_INITIALIZE_START',
    LOGIN_INITIALIZE_FINISH: 'LOGIN_INITIALIZE_FINISH',
    LOGIN_SET_USERNAME: 'LOGIN_SET_USERNAME',
    LOGIN_SET_PASSWORD: 'LOGIN_SET_PASSWORD',
    LOGIN_MODE: 'LOGIN_MODE',
    REGISTER_SUBMIT: 'REGISTER_SUBMIT',
    LOGIN_SUBMIT: 'LOGIN_SUBMIT',
    ERROR_MESSAGE: 'ERROR_MESSAGE',
    SHOW_SPINNER: 'SHOW_SPINNER',
    RECOVER_PASSWORD: 'RECOVER_PASSWORD',
    LOGIN_SET_CURRENT_LANGUAGE: 'LOGIN_SET_CURRENT_LANGUAGE',
}