export default weekTransactionConstants = {
    WEEK_TRANSACTION_INITIALIZE_START: 'WEEK_TRANSACTION_INITIALIZE_START',
    WEEK_TRANSACTION_INITIALIZE_FINISH: 'WEEK_TRANSACTION_INITIALIZE_FINISH',
    WEEK_TRANSACTION_NEW_TRANSACTION: 'WEEK_TRANSACTION_NEW_TRANSACTION',
    SET_WEEK_TRANSACTIONS: 'SET_WEEK_TRANSACTIONS',
    CHANGE_WEEK: 'CHANGE_WEEK',
    SET_WEEK_BALANCE_INFO: 'SET_WEEK_BALANCE_INFO',
    UPDATE_WEEK_TRANSACTION: 'UPDATE_WEEK_TRANSACTION',
    SET_WEEK_TRANSACTION_TO_DETAIL: 'SET_WEEK_TRANSACTION_TO_DETAIL',
    WEEK_TRANSACTION_REMOVE_TRANSACTION: 'WEEK_TRANSACTION_REMOVE_TRANSACTION',


} 
