export const WEEK_TRANSACTION_INITIALIZE_START = 'WEEK_TRANSACTION_INITIALIZE_START';
export const WEEK_TRANSACTION_INITIALIZE_FINISH = 'WEEK_TRANSACTION_INITIALIZE_FINISH';
export const WEEK_TRANSACTION_NEW_TRANSACTION = 'WEEK_TRANSACTION_NEW_TRANSACTION';
export const WEEK_TRANSACTION_SET_TRANSACTION_TO_DETAIL = 'WEEK_TRANSACTION_SET_TRANSACTION_TO_DETAIL';
export const SET_WEEK_TRANSACTIONS = 'SET_WEEK_TRANSACTIONS';
export const CHANGE_WEEK = 'CHANGE_WEEK';
export const SET_WEEK_BALANCE_INFO = 'SET_WEEK_BALANCE_INFO';