export default weekTransactionConstants = {
    WEEK_TRANSACTION_INITIALIZE_START: 'WEEK_TRANSACTION_INITIALIZE_START',
    WEEK_TRANSACTION_INITIALIZE_FINISH: 'WEEK_TRANSACTION_INITIALIZE_FINISH',
    SET_WEEK_TRANSACTIONS: 'SET_WEEK_TRANSACTIONS',
    CHANGE_WEEK: 'CHANGE_WEEK',
    SET_WEEK_BALANCE_INFO: 'SET_WEEK_BALANCE_INFO',
    WEEK_TRANSACTION_SET_USER_CURRENCY: 'WEEK_TRANSACTION_SET_USER_CURRENCY'


} 
