export const DAY_TRANSACTION_INITIALIZE_START = 'DAY_TRANSACTION_INITIALIZE_START';
export const DAY_TRANSACTION_INITIALIZE_FINISH = 'DAY_TRANSACTION_INITIALIZE_FINISH';
export const CHANGE_DATE = 'CHANGE_DATE';
export const SET_DAY_TRANSACTIONS = 'SET_DAY_TRANSACTIONS';
export const SAVE_NEW_TRANSACTION = 'SAVE_NEW_TRANSACTION';
export const SHOW_DETAIL_MODAL = 'SHOW_DETAIL_MODAL';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const SET_TRANSACTION_TO_DETAIL = 'SET_TRANSACTION_TO_DETAIL';
export const SET_BALANCE_INFO = 'SET_BALANCE_INFO';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';

