export const DAY_TRANSACTION_INITIALIZE_START = 'DAY_TRANSACTION_INITIALIZE_START';
export const DAY_TRANSACTION_INITIALIZE_FINISH = 'DAY_TRANSACTION_INITIALIZE_FINISH';
export const CHANGE_DATE = 'CHANGE_DATE';
export const SET_DAY_TRANSACTIONS = 'SET_DAY_TRANSACTIONS';