export default dayTransactionsConstants = {
    DAY_TRANSACTION_INITIALIZE_START: 'DAY_TRANSACTION_INITIALIZE_START',
    DAY_TRANSACTION_INITIALIZE_FINISH: 'DAY_TRANSACTION_INITIALIZE_FINISH',
    CHANGE_DATE: 'CHANGE_DATE',
    SET_DAY_TRANSACTIONS: 'SET_DAY_TRANSACTIONS',
    SET_BALANCE_INFO: 'SET_BALANCE_INFO',
    DAY_TRANSACTION_SET_USER_CURRENCY: 'DAY_TRANSACTION_SET_USER_CURRENCY'
}
