export default settingsConstants = {
    SETTINGS_INITIALIZE_START: 'SETTINGS_INITIALIZE_START',
    SETTINGS_INITIALIZE_FINISH: 'SETTINGS_INITIALIZE_FINISH',
    SETTINGS_SET_CURRENT_LANGUAGE: 'SETTINGS_SET_CURRENT_LANGUAGE'
}
