export default monthTransConstants = {
    MONTH_TRANSACTION_INITIALIZE_START: 'MONTH_TRANSACTION_INITIALIZE_START',
    MONTH_TRANSACTION_INITIALIZE_FINISH: 'MONTH_TRANSACTION_INITIALIZE_FINISH',
    MONTH_TRANSACTION_NEW_TRANSACTION: 'MONTH_TRANSACTION_NEW_TRANSACTION',
    MONTH_TRANSACTION_SET_TRANSACTION_TO_DETAIL: 'MONTH_TRANSACTION_SET_TRANSACTION_TO_DETAIL',
    SET_MONTH_TRANSACTIONS: 'SET_MONTH_TRANSACTIONS',
    CHANGE_MONTH: 'CHANGE_MONTH',
    SET_MONTH_BALANCE_INFO: 'SET_MONTH_BALANCE_INFO',
    UPDATE_MONTH_TRANSACTION: 'UPDATE_MONTH_TRANSACTION',
    SET_MONTH_TRANSACTION_TO_DETAIL: 'SET_MONTH_TRANSACTION_TO_DETAIL',
    MONTH_TRANSACTION_REMOVE_TRANSACTION: 'MONTH_TRANSACTION_REMOVE_TRANSACTION'
}
