export default monthTransConstants = {
    MONTH_TRANSACTION_INITIALIZE_START: 'MONTH_TRANSACTION_INITIALIZE_START',
    MONTH_TRANSACTION_INITIALIZE_FINISH: 'MONTH_TRANSACTION_INITIALIZE_FINISH',
    SET_MONTH_TRANSACTIONS: 'SET_MONTH_TRANSACTIONS',
    CHANGE_MONTH: 'CHANGE_MONTH',
    SET_MONTH_BALANCE_INFO: 'SET_MONTH_BALANCE_INFO',
    MONTH_TRANSACTION_SET_USER_CURRENCY: 'MONTH_TRANSACTION_SET_USER_CURRENCY'
}
