
const constants = {
    routName: {
        splash: 'Splash',
        login: 'Login',
        tabs: 'Tab',
        moneyManager: 'MoneyManager',
        accounts: 'Accounts',
        transactions: 'Transactions',
        newTransaction: 'NewTransaction',
        accountDetail: 'AccountDetail'
    },
    loginMode:{
        register: 'Register',
        logIn: 'LogIn',
        forgotPassword: 'ForgotPassword'
    },
    tabMode: {
        account: 'Account',
        transaction: 'Transaction',
        settings: 'Settings',
        report: 'Report'         
    },
    timeMode: {
        day: 'Day',
        week: 'Week',
        month: 'Month',
        year: 'Year'
    },

    localId: {
        transaction: 'transaction_',
        account: 'account_'
    },

    collection: {
        transactions: 'transactions',
        accounts: 'accounts',
        categories: 'categories',
        currency: 'currency',
        accountTypes: 'accountTypes'
    },

    asyncStorageItem: {
        CATEGORIES: 'CATEGORIES',
        CURRENCIES: 'CURRENCIES',
        ACCOUNT_TYPES: 'ACCOUNT_TYPES',
        USER_LANGUAGE: 'USER_LANGUAGE',
        USER_CURRENCY: 'USER_CURRENCY',
        TRANSACTIONS_BY_CATEGORY: 'TRANSACTIONS_BY_CATEGORY',
        USER_ACCOUNTS: 'USER_ACCOUNTS',
        USER_TRANSACTIONS: 'USER_TRANSACTIONS',
        USER_ID: 'USER_ID',
        RATES: 'RATES'
    },

    sqliteTable: {
        account: 'account',
        accountType: 'accountType',
        category: 'category',
        categorySubcategory: 'categorySubcategory',
        currency: 'currency',
        imageIcon: 'imageIcon',
        subCategory: 'subCategory',
        transactions: 'transactions'
    },

    transactionIcons:{
        cash: require('../assets/images/cash-filled-64.png'),
        card: require('../assets/images/credit-card-64.png'),
        hausing: require('../assets/images/home-64.png'),
        income: require('../assets/images/profit-64.png'),
        gifts: require('../assets/images/gift-64.png'),
        gas: require('../assets/images/gas-64.png'),
        utilities: require('../assets/images/water-64.png'),
        food: require('../assets/images/food-64.png'),
        transportation: require('../assets/images/train-64.png'),
        health: require('../assets/images/health-64.png'),
        savings: require('../assets/images/money-box-64.png'),
        daily: require('../assets/images/shirt-64.png'),
        children: require('../assets/images/children-64.png'),
        obligations: require('../assets/images/debt-64.png'),
        business: require('../assets/images/business-64.png'),
        entertainment: require('../assets/images/tickets-64.png'),
        subscriptions: require('../assets/images/renew-64.png'),
        water: require('../assets/images/water-64.png'),
        trash: require('../assets/images/icons8-waste-50.png'),
        sewer: require('../assets/images/icons8-sewer-50.png'),
        phone: require('../assets/images/icons8-cell-phone-50.png'),
        utilitiesOther: require('../assets/images/lightning-bolt-64.png'),
        internet: require('../assets/images/icons8-internet-50.png'),
        electricity: require('../assets/images/icons8-spiral-bulb-50.png'),
        cable: require('../assets/images/icons8-tv-50.png'),
        vehicle: require('../assets/images/icons8-fiat-500-50.png'),
        registration: require('../assets/images/icons8-licence-50.png'),
        publicTransport: require('../assets/images/icons8-bus-50.png'),
        transportationOther: require('../assets/images/icons8-sedan-50.png'),
        license: require('../assets/images/icons8-identity-theft-50.png'),
        vehicleInsurance: require('../assets/images/icons8-vehicle-insurance-50.png'),
        fuel: require('../assets/images/icons8-gas-station-50.png'),
        video: require('../assets/images/icons8-tv-show-50.png'),
        software: require('../assets/images/icons8-software-50.png'),
        subscriptionsOther: require('../assets/images/renew-64.png'),
        musicSubscription: require('../assets/images/icons8-spotify-50.png'),
        magazine: require('../assets/images/icons8-magazine-50.png'),
        game: require('../assets/images/icons8-game-controller-50.png'),
        investment: require('../assets/images/icons8-duration-finance-50.png'),
        emergency: require('../assets/images/icons8-siren-50.png'),
        retirement: require('../assets/images/icons8-retired-50.png'),
        vacationSave: require('../assets/images/icons8-beach-50.png'),
        savingsOther: require('../assets/images/money-box-64.png'),
        studies: require('../assets/images/icons8-classroom-50.png'),
        car: require('../assets/images/icons8-sedan-50.png'),
        studentLoan: require('../assets/images/icons8-student-center-50.png'),
        obligationsOther: require('../assets/images/debt-64.png'),
        loan: require('../assets/images/icons8-bank-building-50.png'),
        legal: require('../assets/images/icons8-law-50.png'),
        creditCard: require('../assets/images/icons8-mastercard-credit-card-50.png'),
        alimony: require('../assets/images/icons8-baby-50.png'),
        dividend: require('../assets/images/icons8-percentage-50.png'),
        incomeGift: require('../assets/images/icons8-receive-cash-50.png'),
        interest: require('../assets/images/icons8-exchange-50.png'),
        wage: require('../assets/images/icons8-cash-in-hand-50.png'),
        incomeOther: require('../assets/images/profit-64.png'),
        tips: require('../assets/images/icons8-donation-50.png'),
        rent: require('../assets/images/icons8-single-bed-50.png'),
        financialAid: require('../assets/images/icons8-community-grants-50.png'),
        veterinarian: require('../assets/images/icons8-dog-50.png'),
        healthOther: require('../assets/images/health-64.png'),
        medicine: require('../assets/images/icons8-pill-50.png'),
        lifeInsurance: require('../assets/images/icons8-treatment-50.png'),
        insurance: require('../assets/images/icons8-umbrella-50.png'),
        doctor: require('../assets/images/icons8-doctor-female-50.png'),
        furnishing: require('../assets/images/icons8-dining-table-light-50.png'),
        appliance: require('../assets/images/icons8-fridge-50.png'),
        mortgage: require('../assets/images/icons8-bank-50.png'),
        hausingOther: require('../assets/images/home-64.png'),
        maintenace: require('../assets/images/icons8-maintenance-50.png'),
        garden: require('../assets/images/icons8-grass-50.png'),
        improvement: require('../assets/images/icons8-increase-50.png'),
        religious: require('../assets/images/icons8-church-50.png'),
        giftOther: require('../assets/images/gift-64.png'),
        gift: require('../assets/images/icons8-birthday-50.png'),
        christmas: require('../assets/images/icons8-christmas-gift-50.png'),
        charity: require('../assets/images/icons8-welfare-50.png'),
        takeAway: require('../assets/images/icons8-deliver-food-50.png'),
        pet: require('../assets/images/icons8-dog-bowl-50.png'),
        foodOther: require('../assets/images/food-64.png'),
        groceries: require('../assets/images/icons8-ingredients-50.png'),
        diningOut: require('../assets/images/icons8-waiter-50.png'),
        vacation: require('../assets/images/icons8-beach-50.png'),
        sports: require('../assets/images/icons8-swimming-50.png'),
        rental: require('../assets/images/icons8-single-bed-50.png'),
        photo: require('../assets/images/icons8-unsplash-50.png'),
        party: require('../assets/images/icons8-party-50.png'),
        entertainmentOther: require('../assets/images/tickets-64.png'),
        music: require('../assets/images/icons8-music-50.png'),
        movie: require('../assets/images/icons8-movie-projector-50.png'),
        hobbies: require('../assets/images/icons8-trekking-50.png'),
        games: require('../assets/images/icons8-steam-50.png'),
        gadget: require('../assets/images/icons8-smartphone-tablet-50.png'),
        electronic: require('../assets/images/icons8-plug-50.png'),
        dvd: require('../assets/images/icons8-dvd-logo-50.png'),
        concert: require('../assets/images/icons8-rock-music-50.png'),
        book: require('../assets/images/icons8-book-50.png'),
        personal: require('../assets/images/icons8-person-50.png'),
        dailyOther: require('../assets/images/icons8-toothpaste-64.png'),
        miscellaneous: require('../assets/images/icons8-soap-dispenser-64.png'),
        laundry: require('../assets/images/icons8-washing-machine-50.png'),
        education: require('../assets/images/icons8-student-center-50.png'),
        clothing: require('../assets/images/icons8-t-shirt-50.png'),
        cleaning: require('../assets/images/icons8-housekeeping-50.png'),
        barber: require('../assets/images/icons8-hair-dryer-50.png'),
        toys: require('../assets/images/icons8-teddy-bear-50.png'),
        supplies: require('../assets/images/icons8-chupa-chups-50.png'),
        school: require('../assets/images/icons8-school-50.png'),
        childrenOther: require('../assets/images/children-64.png'),
        medical: require('../assets/images/icons8-nurse-50.png'),
        lunch: require('../assets/images/icons8-lunchbox-50.png'),
        lesson: require('../assets/images/icons8-soccer-50.png'),
        babysitting: require('../assets/images/icons8-guardian-50.png'),
        businessOther: require('../assets/images/business-64.png'),
        noDeductible: require('../assets/images/icons8-company-50.png'),
        deductible: require('../assets/images/icons8-organization-50.png'),
        taxes: require('../assets/images/icons8-tax-50.png'),
        refund: require('../assets/images/get-cash-64.png'),
        
        spanish: require('../assets/images/spain-flag-80.png'),
        english: require('../assets/images/uk-flag-80.png'),

        southAfrica: require('../assets/images/icons8-south-africa-96.png'),
        brazil: require('../assets/images/icons8-brazil-80.png'),
        india: require('../assets/images/icons8-india-80.png'),
        russia: require('../assets/images/icons8-russian-federation-80.png'),
        turkey: require('../assets/images/icons8-turkey-80.png'),
        southKorea: require('../assets/images/icons8-south-korea-80.png'),
        norway: require('../assets/images/icons8-norway-80.png'),
        hongKong: require('../assets/images/icons8-hongkong-flag-96.png'),
        singapore: require('../assets/images/icons8-singapore-80.png'),
        mexico: require('../assets/images/icons8-mexico-80.png'),
        newZealand: require('../assets/images/icons8-new-zealand-80.png'),
        sweden: require('../assets/images/icons8-sweden-80.png'),
        china: require('../assets/images/icons8-china-80.png'),
        switzerland: require('../assets/images/icons8-switzerland-80.png'),
        canada: require('../assets/images/icons8-canada-80.png'),
        austalia: require('../assets/images/icons8-australia-80.png'),
        japan: require('../assets/images/icons8-japan-80.png'),
        uk: require('../assets/images/uk-flag-80.png'),
        eu: require('../assets/images/icons8-flag-of-europe-80.png'),
        usa: require('../assets/images/icons8-usa-80.png'),

        DEFAULT: require('../assets/images/icons8-cash-filled-64.png')
    },
    defaultTransactionIcon: {
        name: 'DEFAULT',
        icon: require('../assets/images/icons8-cash-filled-64.png')
    },
    languageIcon: {
    },
    swipeConstants: {
        velocityThreshold: 0.1,
        directionalOffsetThreshold: 10
    },
    accountTypesGeneral:{
        name: "accountTypes.general"
    },
    noWifiIcon: require('../assets/images/noWifi96.png'),
    reportMode: {
        income: 'income',
        expenses: 'expenses'
    }
}

export default constants;