export default newTransactionConstants = {
    NEW_TRANSACTION_INITIALIZE_START: 'NEW_TRANSACTION_INITIALIZE_START',
    NEW_TRANSACTION_INITIALIZE_FINISH: 'NEW_TRANSACTION_INITIALIZE_FINISH',
    CHANGE_DATA: 'CHANGE_DATA',
    SET_CATEGORIES: 'SET_CATEGORIES',
    NEW_TRANSACTION_SET_ACCOUNTS: 'NEW_TRANSACTION_SET_ACCOUNTS',
    NEW_TRANSACTION_SET_ICONS: 'NEW_TRANSACTION_SET_ICONS',
    NEW_TRANSACTION_SHOW_DELETE_MODAL: 'NEW_TRANSACTION_SHOW_DELETE_MODAL',
    NEW_TRANSACTION_HIDE_DELETE_MODAL: 'NEW_TRANSACTION_HIDE_DELETE_MODAL'
}
