export const NEW_TRANSACTION_INITIALIZE_START = 'NEW_TRANSACTION_INITIALIZE_START';
export const NEW_TRANSACTION_INITIALIZE_FINISH = 'NEW_TRANSACTION_INITIALIZE_FINISH';
export const CHANGE_DATA = 'CHANGE_DATA';
export const SET_CATEGORIES = 'SET_CATEGORIES';
