export default accountDetailConstant = { ACCOUNT_DETAIL_INITIALIZE_START: 'ACCOUNT_DETAIL_INITIALIZE_START',
    ACCOUNT_DETAIL_INITIALIZE_FINISH: 'ACCOUNT_DETAIL_INITIALIZE_FINISH',
    ACCOUNT_DETAIL_DATA_CHANGE: 'ACCOUNT_DETAIL_DATA_CHANGE',
    ACCOUNT_DETAIL_SET_PICKER_DATA: 'ACCOUNT_DETAIL_SET_PICKER_DATA',
    ACCOUNT_DETAIL_SHOW_DELETE_MODAL: 'ACCOUNT_DETAIL_SHOW_DELETE_MODAL',
    ACCOUNT_DETAIL_HIDE_DELETE_MODAL: 'ACCOUNT_DETAIL_HIDE_DELETE_MODAL'

}
