export const ACCOUNT_LIST_INITIALIZE_START = 'ACCOUNT_LIST_INITIALIZE_START';
export const ACCOUNT_LIST_INITIALIZE_FINISH = 'ACCOUNT_LIST_INITIALIZE_FINISH';
export const SET_ACCOUNT_LIST = 'SET_ACCOUNT_LIST';
export const SET_ACCOUNT_TO_DETAIL = 'SET_ACCOUNT_TO_DETAIL';
export const SAVE_NEW_ACCOUNT = 'SAVE_NEW_ACCOUNT';
