export default accountListConstants = {
    ACCOUNT_LIST_INITIALIZE_START: 'ACCOUNT_LIST_INITIALIZE_START',
    ACCOUNT_LIST_INITIALIZE_FINISH: 'ACCOUNT_LIST_INITIALIZE_FINISH',
    SET_ACCOUNT_LIST: 'SET_ACCOUNT_LIST',
    SET_ACCOUNT_TO_DETAIL: 'SET_ACCOUNT_TO_DETAIL',
    SAVE_NEW_ACCOUNT: 'SAVE_NEW_ACCOUNT',
    SET_ACCOUNTS_BALANCE_INFO: 'SET_ACCOUNTS_BALANCE_INFO'
} 

